project_id = "rizfkjgwhcpwiryyqejx"

[functions.square-booking]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.fetch-podcast-episodes]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.submit-assessment]
verify_jwt = false

[functions.submit-testimonial]
verify_jwt = false

[functions.og-html]
verify_jwt = false

[functions.send-lead-magnet]
verify_jwt = false

[functions.send-booking-reminder]
verify_jwt = false

[functions.admin-assessments]
verify_jwt = false

[functions.add-to-mailchimp]
verify_jwt = false
