export const SITE_URL = "https://freedominterventions.com";

export const excludedSitemapRoutes = new Set([
  "/404",
  "/admin",
  "/admin-login",
  "/after-consultation",
  "/assessment",
  "/booking",
  "/family-portal",
  "/intervention-agreement",
  "/reschedule",
  "/start-contract",
  "/unsubscribe",
  "/split-house",
  "/divorced-parents",
  "/relapse-after-treatment",
  "/schedule",
]);

export const canonicalRouteAliases = new Map([
  ["/about", "/what-makes-matt-different"],
  ["/booking", "/book"],
  ["/schedule", "/book"],
  ["/relapse-after-treatment", "/it-didnt-stick"],
  ["/services", "/which-help-do-we-need"],
  ["/split-house", "/two-households"],
  ["/divorced-parents", "/two-households"],
  ["/blog/how-addiction-progresses-before-families-realize", "/blog/when-families-realize-situation-no-longer-wait-and-see"],
  ["/blog/addiction-progression-families-notice-late", "/blog/when-families-realize-situation-no-longer-wait-and-see"],
  ["/blog/addiction-no-single-breaking-point", "/blog/addiction-family-crisis-without-breaking-point"],
  ["/blog/boundaries-emotional-fatigue", "/blog/strong-boundaries-reduce-emotional-fatigue"],
  ["/blog/castle-boundaries-healthy-limits", "/blog/family-boundaries-castle-metaphor"],
  ["/blog/dual-diagnosis-mental-health-addiction", "/blog/hidden-driver-addiction-untreated-mental-health-dual-diagnosis"],
  ["/blog/early-recovery-balance-growth", "/blog/finding-balance-early-recovery"],
  ["/blog/emotional-avoidance-addiction", "/blog/emotional-avoidance-addiction-family-enabling"],
  ["/blog/high-functioning-addiction-hidden-crisis", "/blog/high-functioning-addiction-success-hides-problem"],
  ["/blog/how-to-talk-to-loved-one-about-addiction", "/blog/talk-to-loved-one-about-addiction"],
  ["/blog/legal-consequences-treatment-leverage", "/blog/legal-consequences-leverage-treatment"],
  ["/blog/love-turns-monitoring-addiction-family", "/blog/love-turns-constant-monitoring-addiction-family"],
  ["/blog/parental-addiction-intervention", "/blog/professional-interventionist-parental-addiction"],
  ["/blog/rebuilding-trust-after-addiction", "/blog/rebuilding-trust-after-addiction-how-healing-really-happens"],
  ["/blog/sports-betting-addiction-hidden-crisis", "/blog/sports-betting-apps-fueling-gambling-addiction"],
  ["/blog/why-professional-interventions-work-for-families", "/blog/why-professional-interventions-work"],
  ["/blog/preparing-for-an-intervention", "/blog/how-to-prepare-for-an-intervention"],
  ["/blog/waiting-for-right-time-addiction-risk", "/blog/waiting-for-the-right-time-addiction-risk"],
]);
